import { handleFetch, GET_OPTIONS, POST_OPTIONS, PUT_OPTIONS } from './base.service.js';


const BASE_PATH = '/demand';

export const findAllDemand = async () => {
    return await handleFetch(`${BASE_PATH}/all`, GET_OPTIONS);
}

export const findAllDemandPending = async () => {
    return await handleFetch(`${BASE_PATH}/all/pending`, GET_OPTIONS);
}

export const findAllDemandByErrorType = async (type) => {
    return await handleFetch(`${BASE_PATH}/all/type/${type}`, GET_OPTIONS);
}

export const findDemandById = async (id) => {
    return await handleFetch(`${BASE_PATH}/id/${id}`, GET_OPTIONS);
}

export const solveDemandById = async (id) => {
    return await handleFetch(`${BASE_PATH}/solve/${id}`, GET_OPTIONS);
}

export const pdfById = async (id) => {
    return await handleFetch(`${BASE_PATH}/pdf/${id}`, GET_OPTIONS);
}

export const createDemand = async (body) => {
    return await handleFetch(`${BASE_PATH}/create`, POST_OPTIONS, body);
}

export const editDemand = async (id, body) => {
    return await handleFetch(`${BASE_PATH}/edit/${id}`, PUT_OPTIONS, body);
}

export const findAllDemandPaged = async (page, limit) => {
    return await handleFetch(`${BASE_PATH}/all-paged/${page}/${limit}`, GET_OPTIONS);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */