import {
    createUser,
    editUser,
} from '../../_services/users.service';
import { validateUser } from './model';

export const createUserEvent = async (body) => {
    validateUser(body);
    return await createUser(body);
}

export const editUserEvent = async (id, body) => {
    validateUser(body);
    return await editUser(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */