export const validateUser = (body) => {
    //const {  } = body;
}

export const transformEntityUser = (entity) => {
    let newEnt = {...entity}
    newEnt.type = newEnt.type?.cod;
    return newEnt;
}

export const buildEmptyUser = () => {
    return {
        uuid: '',
        name: '',
        login: '',
        password: '',
        state: '',
        type: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */