import {
    createLoom,
    editLoom,
} from '../../_services/loom.service';
import { validateLoom } from './model';

export const createLoomEvent = async (body) => {
    validateLoom(body);
    return await createLoom(body);
}

export const editLoomEvent = async (id, body) => {
    validateLoom(body);
    return await editLoom(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */