import {
    findAllLoom,
    findLoomById,
    findAllLoomPaged,
} from '../../_services/loom.service';

export const findAllLoomEvent = async () => {
    return await findAllLoom();
}

export const findLoomByIdEvent = async (id) => {
    return await findLoomById(id);
}

export const findAllLoomPagedEvent = async (page, limit = 8) => {
    return await findAllLoomPaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */