import {
    findAllErrorType,
    findErrorTypeById,
    findAllErrorTypePaged,
} from '../../_services/error_type.service';

export const findAllErrorTypeEvent = async () => {
    return await findAllErrorType();
}

export const findErrorTypeByIdEvent = async (id) => {
    return await findErrorTypeById(id);
}

export const findAllErrorTypePagedEvent = async (page, limit = 8) => {
    return await findAllErrorTypePaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */