export const validateErrorType = (body) => {
    //const {  } = body;
}

export const transformEntityErrorType = (entity) => {
    let newEnt = {...entity}
    newEnt.render_type = newEnt.render_type?.cod;
    return newEnt;
}

export const buildEmptyErrorType = () => {
    return {
        cod: '',
        name: '',
        render_type: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */