import {
    createDemand,
    editDemand,
} from '../../_services/demand.service';
import { validateDemand } from './model';

export const createDemandEvent = async (body) => {
    validateDemand(body);
    return await createDemand(body);
}

export const editDemandEvent = async (id, body) => {
    validateDemand(body);
    return await editDemand(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */