import {
    findAllDemand,
    findDemandById,
    findAllDemandPaged,
} from '../../_services/demand.service';

export const findAllDemandEvent = async () => {
    return await findAllDemand();
}

export const findDemandByIdEvent = async (id) => {
    return await findDemandById(id);
}

export const findAllDemandPagedEvent = async (page, limit = 8) => {
    return await findAllDemandPaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */