import {
    findAllDemand,
    findDemandById,
    findAllDemandPaged,
    findAllDemandByErrorType,
    pdfById,
    findAllDemandPending,
} from '../../_services/demand.service';

export const findAllDemandPendingEvent = async () => {
    return await findAllDemandPending();
}

export const findAllDemandEvent = async () => {
    return await findAllDemand();
}

export const findDemandByIdEvent = async (id) => {
    return await findDemandById(id);
}

export const pdfByIdEvent = async (id) => {
    return await pdfById(id);
}

export const findAllDemandByErrorTypeEvent = async (type) => {
    return await findAllDemandByErrorType(type);
}

export const findAllDemandPagedEvent = async (page, limit = 8) => {
    return await findAllDemandPaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */