export const validateDemand = (body) => {
    //const {  } = body;
}

export const transformEntityDemand = (entity) => {
    let newEnt = {...entity}
    newEnt.user_create = newEnt.user_create?.uuid;
    newEnt.user_close = newEnt.user_close?.uuid;
    newEnt.demand_state = newEnt.demand_state?.cod;
    newEnt.error_detail = newEnt.error_detail?.cod;
    newEnt.loom = newEnt.loom?.uuid;
    return newEnt;
}

export const buildEmptyDemand = () => {
    return {
        uuid: '',
        warp: '',
        weft_quantity: '',
        date_created: '',
        date_closed: '',
        user_create: '',
        user_close: '',
        demand_state: '',
        error_detail: '',
        loom: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */