export const validateUserType = (body) => {
    //const {  } = body;
}

export const transformEntityUserType = (entity) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyUserType = () => {
    return {
        cod: '',
        name: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */