import {
    createDemandState,
    editDemandState,
} from '../../_services/demand_state.service';
import { validateDemandState } from './model';

export const createDemandStateEvent = async (body) => {
    validateDemandState(body);
    return await createDemandState(body);
}

export const editDemandStateEvent = async (id, body) => {
    validateDemandState(body);
    return await editDemandState(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */