import {
    findAllDemandState,
    findDemandStateById,
    findAllDemandStatePaged,
} from '../../_services/demand_state.service';

export const findAllDemandStateEvent = async () => {
    return await findAllDemandState();
}

export const findDemandStateByIdEvent = async (id) => {
    return await findDemandStateById(id);
}

export const findAllDemandStatePagedEvent = async (page, limit = 8) => {
    return await findAllDemandStatePaged(page, limit);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */