export const validateDemandState = (body) => {
    //const {  } = body;
}

export const transformEntityDemandState = (entity) => {
    let newEnt = {...entity}
    return newEnt;
}

export const buildEmptyDemandState = () => {
    return {
        cod: '',
        name: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */