import {
    createRenderType,
    editRenderType,
} from '../../_services/render_type.service';
import { validateRenderType } from './model';

export const createRenderTypeEvent = async (body) => {
    validateRenderType(body);
    return await createRenderType(body);
}

export const editRenderTypeEvent = async (id, body) => {
    validateRenderType(body);
    return await editRenderType(id, body);
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */