export const validateErrorDetail = (body) => {
    //const {  } = body;
}

export const transformEntityErrorDetail = (entity) => {
    let newEnt = {...entity}
    newEnt.type = newEnt.type?.cod;
    return newEnt;
}

export const buildEmptyErrorDetail = () => {
    return {
        cod: '',
        name: '',
        type: '',
    };
}



/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */